/// Flutter icons List_fooddart
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  List_fooddart
///      fonts:
///       - asset: fonts/List_fooddart.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Listfooddart {
  Listfooddart._();

  static const _kFontFam = 'List_fooddart';
  static const _kFontPkg = null;

  static const IconData salad = const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rice = const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lunch = const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
